node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/mjbeltran/arquitectura-microservicios-docker.git', credentialsId: 'github-mjbeltran', branch: 'master'
        }

        dir ('microservices-arq'){
          def pom = readMavenPom file:'pom.xml'
          print pom.version
          env.version = pom.version
        }
        
        dir ('config-server'){
            
                stage('Build') {
                    sh 'pwd'
                    sh 'ls'
                    sh 'mvn clean install'
                }
              
            stage('Sonarqube') {
                        scannerHome = tool 'SonarQubeScanner'
                        withSonarQubeEnv('sonarqube') {
                            sh "${scannerHome}/bin/sonar-scanner"
                        }                   
              }
        }
        
        stage ('Final') {
            build job: 'eureka-server-pipeline', wait: false
        }      
    }

}
