node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/mjbeltran/arquitectura-microservicios-docker.git', credentialsId: 'github-mjbeltran', branch: 'master'
        }

        dir ('microservices-arq'){
          def pom = readMavenPom file:'pom.xml'
          print pom.version
          env.version = pom.version
        }
        
        dir ('config-server'){
            
                stage('Build') {
                    sh 'pwd'
                    sh 'ls'
                    sh 'mvn clean install'
                }

                stage('Image') {
                        def app = docker.build "172.26.0.1:8888/config-server:${env.version}"
                        app.push()
                }

                stage ('Run') {
                    docker.image("172.26.0.1:8888/config-server:${env.version}").run('-p 8888:8888 -h discovery --name discovery')
                }
        }
        
        stage ('Final') {
            build job: 'eureka-server-pipeline', wait: false
        }      
    }

}
